"""Build assets/icons.svg from the Lucide icon set.

Why: hand-drawn icons never matched each other in weight and optical size.
Lucide ships every icon on the same 24x24 grid with the same 2px round-capped
stroke, so the whole set is consistent by construction.

Kept ours:
  · the id names (i-scales, i-judge, ...) so no markup changes are needed
  · colour, via currentColor
  · size, via the CSS .ic scale

Stripped from each icon:
  · width/height attributes  -> size comes from CSS
  · stroke-width             -> stroke comes from CSS, one value for the set

Run:  python3 dev/build_icons_from_lucide.py
"""
import os
import re
import urllib.request

# our icon id  ->  lucide icon name
MAPPING = {
    'i-judge':         'gavel',
    'i-scales':        'scale',
    'i-shield':        'shield',
    'i-witness':       'user-round',
    'i-cap':           'graduation-cap',
    'i-landmark':      'landmark',
    'i-chart-bars':    'chart-column',
    'i-book':          'book-open',
    'i-people':        'users',
    'i-calendar':      'calendar',
    'i-doc':           'file-text',
    'i-gavel':         'gavel',
    'i-doc-check':     'file-check',
    'i-arrow-right':   'arrow-right',
    'i-arrow-left':    'arrow-left',
    'i-arrow-swap':   'arrow-left-right',
    'i-play':          'circle-play',
    'i-check-circle':  'circle-check',
    'i-check':         'check',
    'i-send':          'send',
    'i-doc-lines':     'files',
    'i-chart-line':    'chart-line',
    'i-radar':         'radar',
    'i-gear':          'settings',
    'i-search':        'search',
    'i-chevron-right': 'chevron-right',
    'i-chevron-down':  'chevron-down',
    'i-bell':          'bell',
    'i-logout':        'log-out',
    'i-plus':          'plus',
    'i-download':      'download',
    'i-clock':         'clock',
    'i-flame':         'flame',
    'i-trophy':        'trophy',
    'i-alert':         'triangle-alert',
    'i-gavel-lite':    'hammer',
    'i-menu':          'menu',
    'i-close':         'x',
    'i-filter':        'filter',
    'i-mail':          'mail',
    'i-lock':          'lock',
    'i-user':          'user',
    'i-home':          'house',
    'i-shield-check':  'shield-check',
}

CDN = 'https://unpkg.com/lucide-static@1.52.0/icons/{}.svg'
CACHE = '/tmp/lucide'


def fetch(name):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, name + '.svg')
    if not os.path.exists(path):
        with urllib.request.urlopen(CDN.format(name), timeout=30) as r:
            data = r.read()
        open(path, 'wb').write(data)
    return open(path, encoding='utf-8').read()


HEADER = '''<?xml version="1.0" encoding="UTF-8"?>
<!--
  Adalat AI icon sprite. GENERATED by dev/build_icons_from_lucide.py.

  Icons: Lucide (https://lucide.dev), MIT licensed. Every glyph is on the same
  24x24 grid with the same 2px round-capped round-joined stroke, so the set is
  consistent by construction. Do not hand-edit: edit MAPPING in the script.

  What stays ours:
    · the i-* id names, so page markup never had to change
    · colour, via currentColor
    · size, via the CSS .ic scale
-->
<svg xmlns="http://www.w3.org/2000/svg" style="position:absolute;width:0;height:0;overflow:hidden" aria-hidden="true" focusable="false">
'''


def to_symbol(icon_id, svg_text):
    body = re.search(r'<svg[^>]*>(.*)</svg>', svg_text, flags=re.S).group(1)
    # Lucide repeats stroke settings on every child; drop them so the single CSS
    # value applies to the whole set.
    body = re.sub(r'\s+stroke="[^"]*"', '', body)
    body = re.sub(r'\s+stroke-width="[^"]*"', '', body)
    body = re.sub(r'\s+stroke-linecap="[^"]*"', '', body)
    body = re.sub(r'\s+stroke-linejoin="[^"]*"', '', body)
    # Only the root <svg> carries presentation width/height. Stripping those from
    # children as well would zero the <rect> in calendar, mail and lock and leave
    # only their stray path segments.
    body = re.sub(r'\s+class="ic-fill"', '', body)
    body = '\n'.join('    ' + ln.strip() for ln in body.strip().splitlines())
    return f'  <symbol id="{icon_id}" viewBox="0 0 24 24">\n{body}\n  </symbol>' 


out = [HEADER]
for icon_id, lucide_name in MAPPING.items():
    out.append(to_symbol(icon_id, fetch(lucide_name)) + '\n')
out.append('</svg>\n')

open('assets/icons.svg', 'w').write(''.join(out))
print(f'built assets/icons.svg with {len(MAPPING)} Lucide icons')